http://jx-slides.jx-production.35.243.86.163.nip.io/slides.html

* file:///Users/tedwon/jx/jenkins-x-slides-tedwon/target/generated-slides/slides.html

= Jenkins X - automated CI/CD solution for cloud native apps on Kubernetes

* my PT script at 공감세미나

== Title

안녕하세요~, 원종석 입니다.
제가 이번 시간에는 Jenkins X 라는 오픈소스를 소개해드리려고 합니다.

Jenkins X의 용도는 Kubernetes 상에서의 CI/CD practice를 도와주는 CI/CD 도구이자 솔루션이라고 할 수 있는데요.
만약에 아직 Kubernetes에 경험이 없으시거나 하지만 Kubernetes에 관심이 있으신 분들에게 도움이 되것 같습니다.

== I am a Red Hat JBoss Senior SME at Seoul

제 소개는 빅데이터 플랫폼 개발을 주로 했었구요, 뉴스 추천이라든지 올레TV의 실시간 시청률 시스템을 개발했구요.  라인 모바일 광고 플랫폼에서 로그 수집 분석이런 부분들 개발을 했습니다.

== Software Maintenance Engineer

현재는 Red Hat에서 JBoss 미들웨어 관련으로 기술 지원 업무를 하고 있습니다.

== Jenkins vs Jenkis X

== Jenkins

Jenkins 자체는 이미 많은 개발자 분들이 알고 계실 꺼에요.
2004년에 Hudson이라는 이름으로 시작이되었죠.
Jenkins 덕분에 우리가 좀 더 자주 빌드를 할 수 있게됐고 그래서 소스 코드에 결함이 없는지를 지속적으로 체크하기 쉽게 되었습니다.
단순하게 빌드뿐만이 아니라 plugin으로 기능을 확장하면서 더 다양한 작업이 가능해졌구요. 
제가 있던 팀에서는 Jenkins가 배치 잡 서버였습니다. 너무나 중요한 핵심 인프라였기 때문에 팀에서 절대적인 availiablity 를 원했습니다. 
그래서 이중화 구성이라든지, 다른 제품이라든지 다양한 개선 방안을 고려했었는데요 결국 마땅한 방법이 없었습니다. 
하지만 이제는 kubernetes나 mesos/marathon 같은 다른 차원의 접근이자 방법이 생긴거죠.


== Jenkins

Jenkins 자체는 시간이 지날 수록 성장하고 있고 계속해서 더 많이 쓰이고 있는 CI/CD 솔루션입니다.


== Jenkins X

Jenkins X 의 로고 이미지가 Jenkins 와 약간 다르죠? 먼가 차이가 느껴지시나요?

Jenkins X는 Kubernetes 상에서의 CI/CD를 지원하는 오픈 소스 도구 입니다.

최근에 Docker나 Kubernetes를 기반으로한 클라우드가 대세가 되면서 주변엣 온통 클라우드 얘기만하는데요, 막상 제대로된 전문가라든지 프랙티스라든지 잘 정리된 자료가 없는 것 같더라구요.
개인적으로 너무나 막막했습니다. 근데 재밋게도 Jenkins X를 테스트해면서 느낀점이.
Jenkins X가 진입 포인트가 되줄 수 있을 것 같더라구요.
Jenkins X를 통해서 Kubernetes와도 친해지고 Kubernetes 상에서의 CI/CD에 대해서도 친해질 수 있습니다.
말그대로 새로운 플랫폼의 시대에도 개발자들이 서비스 개발에만 집중 할 수 있도록 도와주는 강력하게 추천드리는 오프소스 도구입니다.


== Jenkins X - What we need to do

Code change => Pull Request => Review

=> Merge => Staging => Production

Jenkins X 에 대해서 자세하게 설명을 드리고 싶은데 장황하게 들릴 수도 있고 어렵게 들릴 수 도 있을 것 같아요. 그래서 먼저 한가지 정리를 하고 넘어가고 싶은데요.
실제 Jenkins X를 쓰면 우리가 해야하는 일이 특별히 뭐가 달라지는게 아니라 그존 방식 드대로고 실제 개발 작업에만 집중할 수 있게 해준다는 것입니다.
(코드를 변경하고 Pull Request를 보내고 리뷰를 하고 머지를 하면 자동으로 Stage에 반영이 되고 최종적인 결정을 내리면 운영에 배포를 하고 하는 것입니다.)


== What are the changes?

이제 앞으로 대부분의 개발 환경, 개발 플랫폼, 운영 플랫폼이 클라우드 기반으로 크게 변경될 것입니다. 
이 미래는 생각보다 빨리 올 것 같고요, 
이 변화는 지금까지와는 차원이 다른 가장 큰 변화가 될 것 같습니다.
그 변화는 사실 이미 시작되었구요. 하나의 사례로 미국 법무부가 이미 클라우드 기반으로 전환을 했습니다. 
미국 국방부도 클라우드로 전환하기위해서 대규모의 프로젝트를 준비 중에 있습니다.(RFP를 발송하였습니다.) 
국내에서도 진행 중인 사례가 있습니다.
Red Hat은 Kubernetes를 랩핑한 OpenShift 라는 제품을 제공하고 있고 다른 벤더들도 유사한 방식으로 클라우드 플랫폼을 제공하고 있습니다. 
Kubernetes 는 산업상의 표준이라고 할 수 있는데요.
현재 kubernetes 를 기반으로 하는 에코시스템 기술들이 매우 빠르게 발전되고 있습니다. 
이제는 Kubernetes 가 "OS" 같은 환경입니다. 
기존에는 베어메탈이나 VM 에서 작업을 했는데 이제는 컨테이너로 말아서 클라우드에 올리는 방식으로 변경되는거고,
컨터이너는 임뮤터블한 특징을 가지고 있기 때문에 그에 따른 접근 방식이 달라지게되고요,
한덩어리에 몰노리틱 애플리케이션에서 더 작고 더 가볍고 더 많은 애플리케이션으로, 즉 마이크로서비스로 개발되고 운영되고,
이에 따라 개발 팀은 더욱 더 편리하고 개발에 도움이 되는 CI/CD 도구와 프랙티스가 요구됩니다.


== What are the challenges?

새로운 변화, 새로운 플랫폼은 우리에게 새로운 도전이 됩니다.
어떻게하면 나의 애플리케이션을 클라우드로 마이그레이션 할 수 있을지?
Kubernetes 상에서 어떻게 일해야 하는건지?
애플리케이션 개발 / 빌드 / 배포는 어떻게해야 하는건지?
애플리케이션 로그를 보는 방법은 어떻게 되는 건지...
여러가지 잘 모르겠고, 막막한 부분들이 있는데요...

아마도 Jenkins X 가 시작하는데 도움이 될 것 같습니다.


== Started by James Strachan

Jenkins X 하면 James Strachan을 빼놓고 얘기할 수가 없구요.

== Started by James Strachan

이 트윗은 올해 3월에 James Strachan님이 올린 트잇인데요.
스스로 Jenkins X를 만들고 스스로 자축을 하면서 올릿 트윗입니다.

== Started by James Strachan

Jenkins X 는 올해 3월에 처음으로 릴리즈 되었습니다. 
James Strachan이라는 분은 매우 휼륭하고 존경받는 현역 개발자 분이십니다. Groovy 언어를 만드신 분이시고 Apache ActiveMQ 와 Apache Camel을 만드신 분이시구요.
Scala라는 프로그래밍 언어 엄청 뜰 때 자신 만든 Groovy 언어보다 Scala가 더 뛰어나다고 하셨던 일화가 유명한데요. 그만큼 권위의식이 없으시고 지금도 새로운 것을 계속해서 만들어가시는 훌륭한 분이십니다.


== Started by James Strachan

사실 James Strachan은 2017 작년 말까지 Red Hat에 계셨구요.
Red Hat에서 gofabric8 라는 Jenkins X 하고 매우 유사 프로젝트를 진행해왔습니다. 사실 모태가된 프로젝트이구요.
사실 James Strachan 팀이 회사를 옮긴 것이구요. 이미 openshift 를 기반으로 CI/CD 솔루션을 만들던 경험이 있기 때문에 이직한지 단 3개월만에 새로운 오픈소스를 릴리즈 한 것 입니다. 
현재 jenkins X는 몇 시간마다 새로운 릴리즈가 출시되고 있구요,
Jenkins X의 커뮤니티는 상당히 활발한 상태입니다. 
질문을 하면 James Strachan님이 직접 답을 주시고 다른 분들도 열정적으로 답을 잘 주십니다. 
저도 질문을 올리고 답변을 받고 있습니다.


== Features of Jenkins X

Jenkins x 가 제공하는 피쳐는 간단하게 다음 4가지로 정리 할 수 있습니다. 

//자동화된 CI/CD 구성!
//git을 기반으로 자동화된 환경 관리!
//Preview 환경 제공!
//자동 코멘트 기능!


첫번째, 자동화된 CI/CD, 이뜻은,
Jenkins Pipeline 같은 것을 우리가 잘 몰라도 쓸 수 있게끔 자동으로 기본 세팅을 해준다는 의미입니다. 일단 자동 세팅이 되면 우리에 필요에 따라서 커스터마이징해서 사용하면됩니다.

두번째는, git을 기반으로 자동화된 환경 관리를 해주는데요.
이 의미는 각 개발/Staing/Production 같은 논리적인 환경 정의를 Kubernetes의 namespace 단위로 쪼개서 시스템적으로 관리해줍니다.
여기서 GitOps 라는 것은 별거는 아니고 git을 기반으로 버전을 관리하면서 Pull Request 방식으로 작업을하는 git을 기반으로 개발을하는 practice를 말합니다.

세번째, Preview 환경 제공의 의미는 
코드 변경에 따른 Pull Request 가 생성되면 자동으로 Preview 환경을 생성해줍니다. 이것은 Pull Request를 리뷰하는 리뷰어에게 큰 도움이되는 기능입니다.

네번째, 자동 코멘트 기능이 있는데요,
빌드가 완료되었거나 preview 환경이 준비가 완료됐을 때 이슈나 Pull Request에 자동으로 feedback 코멘트가 달리는 기능입니다, 
이 역시 개발자들이 좀 더 손쉽게 상황을 파악하는데 도움을 주는 기능입니다. 

제대로된 즉 진짜 개발에 도움이되는 CI/CD는 결국 도구+경험인데요. 진짜 개발을 해본 전문가가 도구도 만들어야 하고 경험도 제공해주어야 합니다. 커스터마이징이 가능해야 합니다. 
그렇치 않으면 또 우리의 현실은 우울합니다. Agile에 Sprint에 더 빨리 더 높이, 결국에는 실수를 하고 당황하고 얼굴 빨게지고 밤에 잠 못 자고 고생합니다.
제 생각에는 Jenkins X가 마치 전문가가와서 Kubernetes상에서 CI/CD는 이렇게 써라하고 세팅해주고 컨설팅 해주는 것과 같은 느낌이라고 할 수 있습니다.
그래서 우리는 더 빨리 배울 수 있고 더 빨리 개발에 집중할 수 있게됩니다.
Jenkins X 덕분에 당장 Kubernetes 에서 뭔가 해볼 수 있게됩니다.



== Supported Cloud Providers

Jenkins X 가 지원하는 Kubernetes provider는

* Google
* OpenShift
* Amazon
* Azure
* IBM
* Oracle 등이 있구요,
로컬에서 테스트해볼 수있는 환경도 지원합니다.

이게 또 무슨 의미냐하면, Jenkins X 를 쓰면 동일한 명령으로 각각의 cluster 로 context switching하면서 멀티 클러스터를 사용할 수 있게 된다는 의미입니다.



== How does Jenkins X help?

처음에 Kubernetes cluster에 Jenkins X를 설치하면, Jenkins, Nexus, Helm, Tiller, Chartmuseum, Monocular 등이 설치가 됩니다.
Helm 은 yum이나 homebrew 같은 Kubernetes 에서 사용하는 Package manager 입니다.
yum install 해서 애플리케이션을 설치하듯이 helm install 하는 방식으로 Kubernetes에 애플리케이션을 배포할 수 있습니다.
Chartmuseum 은 Helm Chart 저장소입니다.

== Helm Chart

Helm Chart는 Kubernetes 애플리케이션의 패키징 포멧입니다.
이 포멧에 맞춰서 의존성을 정의하고 애플리케이션을 패키징해놓으면 Chartmuseum에 저장되어 있다가. helm install 명령으로 애플리케이션을 Kubernetes에 설치 할 수 있습니다.
Monocular 는 app market처럼 설치가능한 helm chart를 검색할 수 있는 웹 UI 도구입니다.

== Jenkins UI

이 화면은 Jenkins UI 인데요, Jenkins X가 자동으로 설치해주고 pod이라고해서 container로 뛰워줍니다. 그리고 자동으로 프로젝트 세팅을 해줍니다.

== Jenkins Blue Ocean UI

이 화면은 참고로 Jenkins Blue Ocean 이라는 새로운 Jenkins UI 이구요, 

== Jenkins Blue Ocean UI

Jenkins Blue Ocean에서는 Jenkins Pipleline 실행을 실시간 형태로 볼 수 있습니다.

== Nexus UI

이 화면은 Nexus UI 이구요.

== Monocular UI

그리고 이 화면은 Monocular UI 입니다.


== How does Jenkins X help?

Jenkins X 는 사실상 "jx"라는 코멘드 라인 도구라고 보시면 되구요.
Jenkins X를 설치하면 앞서 말씀드린 여러가지 도구들이 자동으로 설치되고 container로 실행이됩니다.
터미널에서 jx open 이렇게 명령을 치시면 CI/CD 도구들과 URL을 확인 할 수 있습니다.

----
jx open

jenkins                   http://jenkins.jx.35.200.29.158.nip.io
jenkins-x-chartmuseum     http://chartmuseum.jx.35.200.29.158.nip.io
jenkins-x-docker-registry http://docker-registry.jx.35.200.29.158.nip.io
jenkins-x-monocular-ui    http://monocular.jx.35.200.29.158.nip.io
nexus                     http://nexus.jx.35.200.29.158.nip.io
----

== Import Maven Project

하나의 애플리케이션 예로 Java Maven Project를 보면요, 원래있는 pom.xml 파일 src 디렉토리외로 뭔가 추가로 Jenkins X가 자동으로 추가해주는 부분이 있습니다.

== Dockerfile

Java Project에 맞는 기본적인 Dockerfile을 정의해줍니다.

== Jenkinsfile

그리고 프로젝트와 Java Maven 빌드를 할 수 있도록 Jenkins Pipeline 도 정의해줍니다.

== Built-in Packs

이게 Built-in Packs 이라고해서요 각 언어에 맞춰서 템플릿같은 것을 준비해놓고 제공해줍니다.

== Built-in Packs

보시면 이 빌트인 팩에는 랭기쥐별로 준비가 되어 있습니다. golang이라던지 php, python 이런 것들도 보이구요.


== Environment Promotion via GitOps

터미털에서 "jx env" 하고 명령을 치시면 현재 환경 정의된 것을 확인할 수 있구요, 다른 환경으로 스위칭할 수 있습니다.
기본적으로 dev, staging, production 이 세팅이 되고, 커스텀 추가하거 삭제할 수 있습니다.

== jx get environments

Staging은 자동으로 promotion 하게되어 있구요.
Production은 수동으로 promotion 하게되어 있는 것을 볼 수 있습니다.

== Demo & Environment Git Repository

환경 정보는 git으로 관리되구요. 생성하시면 github에 이런식으로 demo랑 environment 레파지토리가 생성됩니다.


== jx get applications

jx get apps는 배포된 애플리케이션을 확인 할 수 있습니다. 버전, 현재 stage를 확인할 수 있습니다.


== jx get previews

jx get preview 명령으로 Pull Request에 대한 preview 애플리케이션의 리스트와 URL을 확인 할 수 있습니다.

== Environments in Kubernetes

이 다이어그램을 보시면 Kubernetes 상에 namespace 로 environment 가 정의되어 있구요.
code change에 의해서 preview가 제공되고 upstream master에 merge가 되면 Jenkins로 빌드가 되고 staging에 배포를 합니다. 그리고 Production에 반영할 때는 jx promote 하면 production에 이관이됩니다.


== jx Overview

이 그림은 전체 흐름을 다 설명해주고 있습니다.
프로젝트에 Pull Request가 생성되면 빌드하고 패키징해서 Preview 애플리케이션을 배포하고 upstream에 merge가되면 Staging에 자동으로 배포가되고 담당자가 최종 결정을 내리면 사람이 수동으로 jx promote 명령을 내려서 운영에 배포합니다.


== How do we setup Kubernetes + Jenkins X?

Mac 에서는 homebrew로 아주 간편하게 jx command 를 설치할 수 있습니다.


== How do we setup Kubernetes + Jenkins X?

구글 클라우드 GKE 처럼 퍼블릭 클라우드 환경이라면 jx create cluster 로 명령을 내려서 Kubernetes cluster를 생성하고 Jenkins X 설치를 한 번에 다같이 생성 할 수 있습니다.

== How do we setup Kubernetes + Jenkins X?

만약 이미 Kubernetes cluster 가 있다면 jx install --provider 명령으로 Jenkins X를 설치하면 됩니다.

== Create Cluster GKE

우선 Quick Start로 가장 추천하는 방법은 gmail 계정을 가지고 계시면 

== Create Cluster GKE

Google Cloud Platform에서 300 달러 무료 credit으로 사용해 볼 수 있습니다.
저도 무료 크레딧으로 테스트를 해봤습니다.

== VSCode Jenkins X Extension

참고로 VSCode 를 사용하시면 Jenkins X Extension 설치하고 Pipleline이 동작하는 것을 이 안에서 확인해볼 수가 있습니다.

== Demo

데모인데요, 순서를 정리해보면 

Kubernetes cluster 생성하고

샘플 애플리케이션 생성하고

code change를 적용해보고

Production에 promotion 해보는 과정입니다.

그런데 시간이 꽤 걸리는 작업이라서 모두 다 완전히 못 할 수도 있을 것 같고요.
최대한 한 번 진행해보겠습니다.

== 동영상

사실 이 동영상에 모든 과정이 다 들어있습니다. 나중에 참고해보시고요.

== Demo - Deploy Spring Boot app

먼저 gke Kubernetes cluster를 생성합니다.
jx create cluster gke


== Demo - Deploy Spring Boot app

시간이 꽤 오래걸리기 때문에 미리 생성해 두었구요, 녹화를 해두었습니다.
* Create Cluster GKE Record: 
** https://asciinema.org/a/210859


== Demo - Deploy Spring Boot app

jx create spring 하면 샘플 Spring Boot 애플리케이션을 generate 해줍니다.

== Demo - Deploy Spring Boot app

역시 녹화를 따로 해두었는데요, 
* Record: https://asciinema.org/a/210872

직접 한 번 시도를 해보겠습니다.

Jenkins X 가 자동으로 CI/CD pipeline 구성을 해주고요.
git repository 생성도 해줍니다. 
webhooks 등록도 해주고요.
최초에 pipeline 실행을 자동으로 실행시켜줍니다.

== Jenkins X - What we need to do

이제부터 처음에 정리했던 순서대로 하는 것입니다.

Code change => Pull Request => Review

=> Merge => Staging => Production

== Demo - Jenkins X on Pull Request

이제 코드 체인지를 한 번 해보는데요,

이슈를 생성하고

브랜치를 생성합니다.

새로운 코드를 추가하고요

커밋하고 git push를 하고요

pullrequest를 생성합니다.

이제 PR에 대한 preview 빌드를 진행됩니다.

빌드가 완료되면 

preview 명령으로 preview 링크를 확인합니다.


----
jx create issue -t 'add a homepage'

git checkout -b wip

vi src/main/resources/static/index.html

git add src

git commit -a -m 'add a homepage fixes #1'

git push origin wip

jx create pullrequest -t "add a homepage fixes #1"

jx get preview
----

== Demo - Jenkins X on Pull Request

PR에 preview comment도 자동으로 달립니다.

이제 PR 리뷰어가 PR을 merge 합니다.
이제 master가 빌드되고 Stage에 배포됩니다.

//[%step]
* Builds and tests
* Creates preview docker image + helm chart
* Creates a Preview Environment and comments on the PR with the link
** https://github.com/tedwon/demo1030/pull/2


== Demo - Jenkins X promotion via GitOps

이제 마지막으로 이 버전을 Production 에 배포하려고 합니다.
jx promote 에 버전을 명시하고 명령을 내리면 해당 버전이 production에 배포됩니다.

jx promote --version 0.0.2 --env production


== Demo - Jenkins X promotion via GitOps

//[%step]
* Each environment stores its configuration as helm charts in a git repository
** Reuse the Pull Request workflow for changes
* To promote a version to, say, Production Jenkins X submits a Pull Request
** The Promote step waits for the Pull Request CI build to complete


== Jenkins X Roadmap

여기 Roadmap 페이지에서 Jenkins X 에 현재 상태와 지원 범위를 확인해볼 수 있습니다.

You can check the current status of Jenkins X on the roadmap page.
https://jenkins-x.io/contribute/roadmap/


== Jenkins X Slack

각종 궁금한 사항은 Jenkins X 커뮤니티 Slack에서 바로 물어보고 바로 답변을 받을 수 있습니다.


== Jenkins X Slack

James Strachan님이 영국에 계셔서 우리나라 시간으로 오후 4시정도부터는 직접 답변을 해주세요.


== Try it out!

관심있는 분들은 직접 실습 한 번 해보시고요 ,
저희 JBUG 에서는 이미 2차례나 hands-on을 했습니다.
만약 정말 나도 꼭 같이 해보고 싶다 이런 분들이 계시면 연락을 주세요. 그럼 다시 또 진행 하겠습니다.
* https://jenkins-x.io/getting-started/
* JBUG Jenkins X Hands-on https://goo.gl/oBbHxA

== Special Thanks to

Jenkins X를 소개해주신 분이 우리 JBUG에 차정호님이십니다. 항상 많이 배우고 있고 이자리를 빌어서 다시 한 번 감사드립니다.
Jungho Cha <jcha@redhat.com>


//[background-color="navy"]
== Thank you

감사합니다.
